name: Preprocessor

on:
  push:
    branches: ['main']
    paths:
      - '**/preprocessor.*'
      - 'sub/*.json'
  schedule:
    - cron: '0 16 * * *'
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-24.04
    strategy:
      matrix:
        dummy: ['single']
    defaults:
      run:
        shell: bash -e {0}

    steps:
      - name: Checkout Repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: Setup PHP
        uses: shivammathur/setup-php@v2
        with:
          php-version: '8.3'

      - name: Run script
        run: php edge/preprocessor.php

      - name: Configure git
        run: |
          git config --local user.name "BotFather"
          git config --local user.email "botfather.rev@proton.me"

      - name: Commit and push changes
        run: |
          git add -A
          if ! git diff --cached --quiet; then
            git commit -m "Cloudflare IPs Refreshed at: $(TZ='Asia/Tehran' date '+%H:%M:%S')" -m "The list of Cloudflare IPs has been updated" --author="Diana-Cl <135276904+Diana-Cl@users.noreply.github.com>"
            git push origin main
          else
            echo "No changes detected. Skipping commit and push."
          fi
